In [1]:
import numpy
numpy.__version__

'1.18.5'

In [2]:
import numpy as np

In [1]:
np.zeros(10, dtype=int)

NameError: name 'np' is not defined

In [2]:
import numpy

In [3]:
import numpy as np

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
np.ones(3,5,dtype=int)

TypeError: ones() got multiple values for argument 'dtype'

In [7]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
np.zeros(50, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full((3,5),12.34)

array([[12.34, 12.34, 12.34, 12.34, 12.34],
       [12.34, 12.34, 12.34, 12.34, 12.34],
       [12.34, 12.34, 12.34, 12.34, 12.34]])

In [11]:
np.arange(6,4)

array([], dtype=int32)

In [12]:
np.arange(6,20,4)

array([ 6, 10, 14, 18])

In [13]:
np.linespace(0,100,5)

AttributeError: module 'numpy' has no attribute 'linespace'

In [14]:
np.linespace(0, 100, 5)

AttributeError: module 'numpy' has no attribute 'linespace'

In [15]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [17]:
np.random.random(1,10)

TypeError: random() takes at most 1 positional argument (2 given)

In [18]:
np.random.random((1,10))

array([[0.1219329 , 0.47837882, 0.9037635 , 0.03185966, 0.13327871,
        0.5869582 , 0.48332761, 0.94558173, 0.0371808 , 0.11134318]])